name: Project publish

on:
  push:
    branches: [ master ]

jobs:
  docker-build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t minecraftserver .;

      - name: Login into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push image to docker hub
        run: docker tag ${{ secrets.DOCKER_REPO }}:latest minecraftserver; docker push ${{ secrets.DOCKER_REPO }}:latest
